### ISSUE TITLE
Not able to access more than one cluster using docker-compose option

### ISSUE THREAD

**Issue by bsunkad** [Dabz/ccloudexporter#73]
Hi 

Using this code, i tried to connect confluent using the docker-compose method.  This code is able to connect and pull the metrics only when I am able to pass CCLOUD_CLUSTER with a single cluster only.   Having the following issues and need resolve.
1. During the single cluster-info through CCLOUD_CLUSTER, not able to get the topics/partitions information.
2. How do I make the docker-compose method pull more than cluster pieces of information along with topics/partitions etc..

Appreciate if anyone able to help me with this.

- Bhaskar

**Comment by Dabz** [comment]
Hi @bsunkad!

In order to do a docker-compose that will fetch the data from multiple CCLOUD_CLUSTER, you will need to provide a custom configuration file. The environment variable allows only one cluster (though it could be improved in the future). Please find bellow an example of docker-compose to provide a custom configuration file:

```
version: '3.1'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus.yml
    command:
      - '--config.file=/prometheus.yml'
    ports:
      - 9090:9090
    restart: always

  ccloud_exporter:
    image: dabz/ccloudexporter
    container_name: ccloud_exporter
    command:
      - '--config=/config.yaml'
    environment:
      CCLOUD_API_KEY: ${CCLOUD_API_KEY}
      CCLOUD_API_SECRET: ${CCLOUD_API_SECRET}
      CCLOUD_CLUSTER: ${CCLOUD_CLUSTER}
      CCLOUD_CONNECTOR: ${CCLOUD_CONNECTOR}
      CCLOUD_KSQL: ${CCLOUD_KSQL}
    volumes:
      - ./config.simple.yaml:/config.yaml
```

You can find examples of configuration files on: https://github.com/Dabz/ccloudexporter/tree/master/config

Let me know if you need further assistance!
